import { Product } from '@/components/products/ProductColumns'

export const getData = async (): Promise<Product[]> => {
    return [
        {
            image: '/images/default-product.png',
            id: 100000001,
            productName: 'Aspirin',
            brandName: 'Bayer Aspirin',
            genericName: 'Aspirin',
            manufacturer: 'Bayer',
            price: 9.99,
            stock: 100,
            since: '2022-01-01',
            updated: '2023-07-01',
        },
        {
            image: '/images/default-product.png',
            id: 100000002,
            productName: 'Ibuprofen',
            brandName: 'Advil',
            genericName: 'Ibuprofen',
            manufacturer: 'Pfizer',
            price: 12.99,
            stock: 200,
            since: '2022-01-15',
            updated: '2023-07-15',
        },
        {
            image: '/images/default-product.png',
            id: 100000003,
            productName: 'Acetaminophen',
            brandName: 'Tylenol',
            genericName: 'Acetaminophen',
            manufacturer: 'Johnson & Johnson',
            price: 11.99,
            stock: 150,
            since: '2022-02-01',
            updated: '2023-07-30',
        },
        {
            image: '/images/default-product.png',
            id: 100000004,
            productName: 'Amoxicillin',
            brandName: 'Amoxil',
            genericName: 'Amoxicillin',
            manufacturer: 'GlaxoSmithKline',
            price: 15.99,
            stock: 80,
            since: '2022-02-15',
            updated: '2023-08-01',
        },
        {
            image: '/images/default-product.png',
            id: 100000005,
            productName: 'Lisinopril',
            brandName: 'Zestril',
            genericName: 'Lisinopril',
            manufacturer: 'AstraZeneca',
            price: 20.99,
            stock: 50,
            since: '2022-03-01',
            updated: '2023-08-15',
        },
        {
            image: '/images/default-product.png',
            id: 100000006,
            productName: 'Metformin',
            brandName: 'Glucophage',
            genericName: 'Metformin',
            manufacturer: 'Merck',
            price: 18.99,
            stock: 120,
            since: '2022-03-15',
            updated: '2023-08-30',
        },
        {
            image: '/images/default-product.png',
            id: 100000007,
            productName: 'Amlodipine',
            brandName: 'Norvasc',
            genericName: 'Amlodipine',
            manufacturer: 'Pfizer',
            price: 22.99,
            stock: 90,
            since: '2022-04-01',
            updated: '2023-09-01',
        },
        {
            image: '/images/default-product.png',
            id: 100000008,
            productName: 'Omeprazole',
            brandName: 'Prilosec',
            genericName: 'Omeprazole',
            manufacturer: 'AstraZeneca',
            price: 25.99,
            stock: 110,
            since: '2022-04-15',
            updated: '2023-09-15',
        },
        {
            image: '/images/default-product.png',
            id: 100000009,
            productName: 'Simvastatin',
            brandName: 'Zocor',
            genericName: 'Simvastatin',
            manufacturer: 'Merck',
            price: 19.99,
            stock: 130,
            since: '2022-05-01',
            updated: '2023-09-30',
        },
        {
            image: '/images/default-product.png',
            id: 100000010,
            productName: 'Hydrochlorothiazide',
            brandName: 'Microzide',
            genericName: 'Hydrochlorothiazide',
            manufacturer: 'Novartis',
            price: 14.99,
            stock: 70,
            since: '2022-05-15',
            updated: '2023-10-01',
        },
        {
            image: '/images/default-product.png',
            id: 100000011,
            productName: 'Atorvastatin',
            brandName: 'Lipitor',
            genericName: 'Atorvastatin',
            manufacturer: 'Pfizer',
            price: 27.99,
            stock: 200,
            since: '2022-06-01',
            updated: '2023-10-15',
        },
        {
            image: '/images/default-product.png',
            id: 100000012,
            productName: 'Losartan',
            brandName: 'Cozaar',
            genericName: 'Losartan',
            manufacturer: 'Merck',
            price: 21.99,
            stock: 180,
            since: '2022-06-15',
            updated: '2023-10-30',
        },
        {
            image: '/images/default-product.png',
            id: 100000013,
            productName: 'Gabapentin',
            brandName: 'Neurontin',
            genericName: 'Gabapentin',
            manufacturer: 'Pfizer',
            price: 23.99,
            stock: 160,
            since: '2022-07-01',
            updated: '2023-11-01',
        },
        {
            image: '/images/default-product.png',
            id: 100000014,
            productName: 'Sertraline',
            brandName: 'Zoloft',
            genericName: 'Sertraline',
            manufacturer: 'Pfizer',
            price: 24.99,
            stock: 140,
            since: '2022-07-15',
            updated: '2023-11-15',
        },
        {
            image: '/images/default-product.png',
            id: 100000015,
            productName: 'Furosemide',
            brandName: 'Lasix',
            genericName: 'Furosemide',
            manufacturer: 'Sanofi',
            price: 16.99,
            stock: 100,
            since: '2022-08-01',
            updated: '2023-11-30',
        },
        {
            image: '/images/default-product.png',
            id: 100000016,
            productName: 'Citalopram',
            brandName: 'Celexa',
            genericName: 'Citalopram',
            manufacturer: 'Lundbeck',
            price: 17.99,
            stock: 110,
            since: '2022-08-15',
            updated: '2023-12-01',
        },
        {
            image: '/images/default-product.png',
            id: 100000017,
            productName: 'Pantoprazole',
            brandName: 'Protonix',
            genericName: 'Pantoprazole',
            manufacturer: 'Pfizer',
            price: 18.99,
            stock: 90,
            since: '2022-09-01',
            updated: '2023-12-15',
        },
        {
            image: '/images/default-product.png',
            id: 100000018,
            productName: 'Trazodone',
            brandName: 'Desyrel',
            genericName: 'Trazodone',
            manufacturer: 'Bristol-Myers Squibb',
            price: 19.99,
            stock: 80,
            since: '2022-09-15',
            updated: '2023-12-30',
        },
        {
            image: '/images/default-product.png',
            id: 100000019,
            productName: 'Rosuvastatin',
            brandName: 'Crestor',
            genericName: 'Rosuvastatin',
            manufacturer: 'AstraZeneca',
            price: 26.99,
            stock: 75,
            since: '2022-10-01',
            updated: '2024-01-01',
        },
        {
            image: '/images/default-product.png',
            id: 100000020,
            productName: 'Carvedilol',
            brandName: 'Coreg',
            genericName: 'Carvedilol',
            manufacturer: 'GlaxoSmithKline',
            price: 22.99,
            stock: 85,
            since: '2022-10-15',
            updated: '2024-01-15',
        },
        {
            image: '/images/default-product.png',
            id: 100000021,
            productName: 'Meloxicam',
            brandName: 'Mobic',
            genericName: 'Meloxicam',
            manufacturer: 'Boehringer Ingelheim',
            price: 24.99,
            stock: 95,
            since: '2022-11-01',
            updated: '2024-01-30',
        },
        {
            image: '/images/default-product.png',
            id: 100000022,
            productName: 'Allopurinol',
            brandName: 'Zyloprim',
            genericName: 'Allopurinol',
            manufacturer: 'Prometheus Laboratories',
            price: 18.99,
            stock: 130,
            since: '2022-11-15',
            updated: '2024-02-01',
        },
        {
            image: '/images/default-product.png',
            id: 100000023,
            productName: 'Cyclobenzaprine',
            brandName: 'Flexeril',
            genericName: 'Cyclobenzaprine',
            manufacturer: 'Teva',
            price: 15.99,
            stock: 140,
            since: '2022-12-01',
            updated: '2024-02-15',
        },
        {
            image: '/images/default-product.png',
            id: 100000024,
            productName: 'Azithromycin',
            brandName: 'Zithromax',
            genericName: 'Azithromycin',
            manufacturer: 'Pfizer',
            price: 19.99,
            stock: 160,
            since: '2022-12-15',
            updated: '2024-02-28',
        },
        {
            image: '/images/default-product.png',
            id: 100000025,
            productName: 'Doxycycline',
            brandName: 'Vibramycin',
            genericName: 'Doxycycline',
            manufacturer: 'Pfizer',
            price: 21.99,
            stock: 170,
            since: '2023-01-01',
            updated: '2024-03-01',
        },
    ]
};

// Product detail schema
export interface DetailProduct {
    id: number
    activeIngredients: string
    inactiveIngredients: string
    therapeuticClass: string
    formulation: string
    systemicCategory: string
    usageDuration: string
    targetPopulation: string
    drugClass: string
    strength: string
    dosage: string
    routeOfAdministration: string
    indications: string
    contraindications: string
    sideEffects: string
    interactions: string
    warnings: string
    storageConditions: string
    approvalDate: string
    expiryDate: string
    batchNumber: string
    description: string
}

export const getDetailData = async (): Promise<DetailProduct[]> => {
    return [
        {
            id: 100000001,
            activeIngredients: 'Aspirin 325mg',
            inactiveIngredients: 'Corn Starch, Hypromellose, Powdered Cellulose',
            therapeuticClass: 'Analgesics',
            formulation: 'Tablets',
            systemicCategory: 'Cardiovascular System',
            usageDuration: 'PRN',
            targetPopulation: 'Adults',
            drugClass: 'NSAIDs',
            strength: '325mg',
            dosage: '1-2 tablets every 4-6 hours',
            routeOfAdministration: 'Oral',
            indications: 'Pain relief, anti-inflammatory, antipyretic',
            contraindications: 'Hypersensitivity to NSAIDs, active peptic ulcer, asthma',
            sideEffects: 'Nausea, gastrointestinal bleeding, dizziness',
            interactions: 'Anticoagulants, other NSAIDs, alcohol',
            warnings: 'Risk of Reye’s syndrome in children, bleeding disorders',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'A12345',
            description: 'Aspirin is used to reduce fever and relieve mild to moderate pain.',
        },
        {
            id: 100000002,
            activeIngredients: 'Ibuprofen 200mg',
            inactiveIngredients: 'Lactose, Microcrystalline Cellulose, Croscarmellose Sodium',
            therapeuticClass: 'Analgesics',
            formulation: 'Tablets',
            systemicCategory: 'Musculoskeletal System',
            usageDuration: 'PRN',
            targetPopulation: 'Adults',
            drugClass: 'NSAIDs',
            strength: '200mg',
            dosage: '1 tablet every 4-6 hours',
            routeOfAdministration: 'Oral',
            indications: 'Pain relief, anti-inflammatory, antipyretic',
            contraindications: 'Hypersensitivity to NSAIDs, active peptic ulcer, severe renal impairment',
            sideEffects: 'Stomach pain, heartburn, dizziness',
            interactions: 'Aspirin, anticoagulants, diuretics',
            warnings: 'Risk of gastrointestinal bleeding, cardiovascular events',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'B12345',
            description: 'Ibuprofen is used to reduce fever and relieve pain or inflammation.',
        },
        {
            id: 100000003,
            activeIngredients: 'Acetaminophen 500mg',
            inactiveIngredients: 'Povidone, Starch, Magnesium Stearate',
            therapeuticClass: 'Analgesics',
            formulation: 'Tablets',
            systemicCategory: 'Nervous System',
            usageDuration: 'PRN',
            targetPopulation: 'Adults',
            drugClass: 'Analgesics',
            strength: '500mg',
            dosage: '1-2 tablets every 4-6 hours',
            routeOfAdministration: 'Oral',
            indications: 'Pain relief, fever reducer',
            contraindications: 'Severe liver disease, hypersensitivity',
            sideEffects: 'Nausea, rash, headache',
            interactions: 'Alcohol, warfarin, other acetaminophen products',
            warnings: 'Risk of liver damage, avoid excessive alcohol consumption',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'C12345',
            description: 'Acetaminophen is used to treat mild to moderate pain and reduce fever.',
        },
        {
            id: 100000004,
            activeIngredients: 'Amoxicillin 500mg',
            inactiveIngredients: 'Magnesium Stearate, Microcrystalline Cellulose, Sodium Starch Glycolate',
            therapeuticClass: 'Antibiotics',
            formulation: 'Capsules',
            systemicCategory: 'Respiratory System',
            usageDuration: 'Acute',
            targetPopulation: 'Adults',
            drugClass: 'Beta-lactam antibiotics',
            strength: '500mg',
            dosage: '1 capsule every 8 hours',
            routeOfAdministration: 'Oral',
            indications: 'Bacterial infections',
            contraindications: 'Hypersensitivity to penicillins',
            sideEffects: 'Nausea, diarrhea, allergic reactions',
            interactions: 'Allopurinol, oral contraceptives, warfarin',
            warnings: 'May cause allergic reactions, avoid if allergic to penicillin',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'D12345',
            description: 'Amoxicillin is used to treat various types of bacterial infections.',
        },
        {
            id: 100000005,
            activeIngredients: 'Lisinopril 10mg',
            inactiveIngredients: 'Calcium Phosphate, Magnesium Stearate, Mannitol',
            therapeuticClass: 'Antihypertensives',
            formulation: 'Tablets',
            systemicCategory: 'Cardiovascular System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'ACE inhibitors',
            strength: '10mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'High blood pressure, heart failure',
            contraindications: 'History of angioedema, pregnancy',
            sideEffects: 'Dizziness, cough, elevated blood potassium',
            interactions: 'Diuretics, potassium supplements, NSAIDs',
            warnings: 'May cause dizziness, monitor kidney function',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'E12345',
            description: 'Lisinopril is used to treat high blood pressure and heart failure.',
        },
        {
            id: 100000006,
            activeIngredients: 'Metformin 500mg',
            inactiveIngredients: 'Magnesium Stearate, Microcrystalline Cellulose, Hypromellose',
            therapeuticClass: 'Antidiabetics',
            formulation: 'Tablets',
            systemicCategory: 'Endocrine System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Biguanides',
            strength: '500mg',
            dosage: '1 tablet twice daily',
            routeOfAdministration: 'Oral',
            indications: 'Type 2 diabetes',
            contraindications: 'Severe renal impairment, metabolic acidosis',
            sideEffects: 'Nausea, diarrhea, abdominal pain',
            interactions: 'Alcohol, cimetidine, iodinated contrast media',
            warnings: 'Risk of lactic acidosis, monitor kidney function',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'F12345',
            description: 'Metformin is used to improve blood sugar control in people with type 2 diabetes.',
        },
        {
            id: 100000007,
            activeIngredients: 'Amlodipine 5mg',
            inactiveIngredients: 'Cellulose, Calcium Phosphate, Magnesium Stearate',
            therapeuticClass: 'Antihypertensives',
            formulation: 'Tablets',
            systemicCategory: 'Cardiovascular System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Calcium channel blockers',
            strength: '5mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'High blood pressure, angina',
            contraindications: 'Severe hypotension, cardiogenic shock',
            sideEffects: 'Swelling, dizziness, fatigue',
            interactions: 'Simvastatin, diltiazem, alcohol',
            warnings: 'May cause dizziness, monitor blood pressure',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'G12345',
            description: 'Amlodipine is used to treat high blood pressure and angina.',
        },
        {
            id: 100000008,
            activeIngredients: 'Omeprazole 20mg',
            inactiveIngredients: 'Lactose, Magnesium Stearate, Titanium Dioxide',
            therapeuticClass: 'Immunosuppressants',
            formulation: 'Capsules',
            systemicCategory: 'Digestive System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Proton pump inhibitors',
            strength: '20mg',
            dosage: '1 capsule daily',
            routeOfAdministration: 'Oral',
            indications: 'GERD, peptic ulcers',
            contraindications: 'Hypersensitivity to omeprazole',
            sideEffects: 'Headache, nausea, diarrhea',
            interactions: 'Clopidogrel, warfarin, digoxin',
            warnings: 'May increase risk of fractures, monitor magnesium levels',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'H12345',
            description: 'Omeprazole is used to treat symptoms of gastroesophageal reflux disease (GERD).',
        },
        {
            id: 100000009,
            activeIngredients: 'Simvastatin 40mg',
            inactiveIngredients: 'Lactose, Microcrystalline Cellulose, Magnesium Stearate',
            therapeuticClass: 'Bronchodilators',
            formulation: 'Tablets',
            systemicCategory: 'Cardiovascular System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Statins',
            strength: '40mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'High cholesterol',
            contraindications: 'Liver disease, pregnancy',
            sideEffects: 'Muscle pain, headache, nausea',
            interactions: 'Warfarin, grapefruit juice, erythromycin',
            warnings: 'Monitor liver function, may cause muscle pain',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'I12345',
            description: 'Simvastatin is used to lower levels of bad cholesterol and fats in the blood.',
        },
        {
            id: 100000010,
            activeIngredients: 'Hydrochlorothiazide 25mg',
            inactiveIngredients: 'Lactose, Magnesium Stearate, Starch',
            therapeuticClass: 'Diuretic',
            formulation: 'Tablet',
            systemicCategory: 'Cardiovascular System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Thiazide diuretics',
            strength: '25mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'High blood pressure, edema',
            contraindications: 'Anuria, hypersensitivity to sulfonamide-derived drugs',
            sideEffects: 'Increased urination, dizziness, electrolyte imbalance',
            interactions: 'Digitalis, lithium, corticosteroids',
            warnings: 'Monitor electrolytes, may cause dizziness',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'J12345',
            description: 'Hydrochlorothiazide is used to treat high blood pressure and fluid retention.',
        },
        {
            id: 100000011,
            activeIngredients: 'Atorvastatin 20mg',
            inactiveIngredients: 'Lactose, Microcrystalline Cellulose, Magnesium Stearate',
            therapeuticClass: 'Lipid-lowering agent',
            formulation: 'Tablet',
            systemicCategory: 'Cardiovascular System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Statins',
            strength: '20mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'High cholesterol',
            contraindications: 'Liver disease, pregnancy',
            sideEffects: 'Muscle pain, headache, nausea',
            interactions: 'Warfarin, grapefruit juice, erythromycin',
            warnings: 'Monitor liver function, may cause muscle pain',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'K12345',
            description: 'Atorvastatin is used to lower levels of bad cholesterol and fats in the blood.',
        },
        {
            id: 100000012,
            activeIngredients: 'Losartan 50mg',
            inactiveIngredients: 'Microcrystalline Cellulose, Lactose, Magnesium Stearate',
            therapeuticClass: 'Antihypertensive',
            formulation: 'Tablet',
            systemicCategory: 'Cardiovascular System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Angiotensin II receptor blockers',
            strength: '50mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'High blood pressure, diabetic nephropathy',
            contraindications: 'Hypersensitivity to losartan',
            sideEffects: 'Dizziness, back pain, upper respiratory infection',
            interactions: 'Lithium, rifampin, NSAIDs',
            warnings: 'Monitor kidney function, may cause dizziness',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'L12345',
            description: 'Losartan is used to treat high blood pressure and protect the kidneys from damage due to diabetes.',
        },
        {
            id: 100000013,
            activeIngredients: 'Gabapentin 300mg',
            inactiveIngredients: 'Lactose, Microcrystalline Cellulose, Magnesium Stearate',
            therapeuticClass: 'Anticonvulsant',
            formulation: 'Capsule',
            systemicCategory: 'Nervous System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Gamma-aminobutyric acid analogs',
            strength: '300mg',
            dosage: '1 capsule three times daily',
            routeOfAdministration: 'Oral',
            indications: 'Seizures, neuropathic pain',
            contraindications: 'Hypersensitivity to gabapentin',
            sideEffects: 'Dizziness, drowsiness, peripheral edema',
            interactions: 'Antacids, alcohol, morphine',
            warnings: 'May cause dizziness or drowsiness, avoid driving or operating heavy machinery',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'M12345',
            description: 'Gabapentin is used to treat seizures and nerve pain.',
        },
        {
            id: 100000014,
            activeIngredients: 'Sertraline 50mg',
            inactiveIngredients: 'Calcium Phosphate, Magnesium Stearate, Microcrystalline Cellulose',
            therapeuticClass: 'Antidepressant',
            formulation: 'Tablet',
            systemicCategory: 'Nervous System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Selective serotonin reuptake inhibitors (SSRIs)',
            strength: '50mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'Depression, anxiety disorders',
            contraindications: 'Concomitant use with MAOIs, hypersensitivity',
            sideEffects: 'Nausea, insomnia, dry mouth',
            interactions: 'MAOIs, pimozide, NSAIDs',
            warnings: 'May increase the risk of suicidal thoughts, monitor for worsening symptoms',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'N12345',
            description: 'Sertraline is used to treat depression and anxiety disorders.',
        },
        {
            id: 100000015,
            activeIngredients: 'Furosemide 40mg',
            inactiveIngredients: 'Lactose, Microcrystalline Cellulose, Magnesium Stearate',
            therapeuticClass: 'Diuretic',
            formulation: 'Tablet',
            systemicCategory: 'Cardiovascular System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Loop diuretics',
            strength: '40mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'Edema, high blood pressure',
            contraindications: 'Anuria, severe electrolyte depletion',
            sideEffects: 'Increased urination, electrolyte imbalance, dizziness',
            interactions: 'Aminoglycosides, NSAIDs, lithium',
            warnings: 'Monitor electrolytes, may cause dehydration',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'O12345',
            description: 'Furosemide is used to treat fluid retention and high blood pressure.',
        },
        {
            id: 100000016,
            activeIngredients: 'Citalopram 20mg',
            inactiveIngredients: 'Lactose, Microcrystalline Cellulose, Magnesium Stearate',
            therapeuticClass: 'Antidepressant',
            formulation: 'Tablet',
            systemicCategory: 'Nervous System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Selective serotonin reuptake inhibitors (SSRIs)',
            strength: '20mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'Depression',
            contraindications: 'Concomitant use with MAOIs, hypersensitivity',
            sideEffects: 'Nausea, dry mouth, drowsiness',
            interactions: 'MAOIs, pimozide, NSAIDs',
            warnings: 'May increase the risk of suicidal thoughts, monitor for worsening symptoms',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'P12345',
            description: 'Citalopram is used to treat depression.',
        },
        {
            id: 100000017,
            activeIngredients: 'Levothyroxine 50mcg',
            inactiveIngredients: 'Lactose, Magnesium Stearate, Microcrystalline Cellulose',
            therapeuticClass: 'Thyroid Hormone',
            formulation: 'Tablet',
            systemicCategory: 'Endocrine System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Thyroid hormones',
            strength: '50mcg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'Hypothyroidism',
            contraindications: 'Untreated thyrotoxicosis, acute myocardial infarction',
            sideEffects: 'Weight loss, palpitations, nervousness',
            interactions: 'Calcium supplements, iron supplements, antacids',
            warnings: 'Monitor thyroid function, may cause hyperthyroidism',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'Q12345',
            description: 'Levothyroxine is used to treat hypothyroidism.',
        },
        {
            id: 100000018,
            activeIngredients: 'Metoprolol 50mg',
            inactiveIngredients: 'Lactose, Magnesium Stearate, Microcrystalline Cellulose',
            therapeuticClass: 'Antihypertensive',
            formulation: 'Tablet',
            systemicCategory: 'Cardiovascular System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Beta-blockers',
            strength: '50mg',
            dosage: '1 tablet twice daily',
            routeOfAdministration: 'Oral',
            indications: 'High blood pressure, angina',
            contraindications: 'Severe bradycardia, heart block greater than first degree',
            sideEffects: 'Dizziness, fatigue, depression',
            interactions: 'Calcium channel blockers, digoxin, NSAIDs',
            warnings: 'May cause dizziness, monitor heart rate',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'R12345',
            description: 'Metoprolol is used to treat high blood pressure and angina.',
        },
        {
            id: 100000019,
            activeIngredients: 'Prednisone 10mg',
            inactiveIngredients: 'Lactose, Magnesium Stearate, Microcrystalline Cellulose',
            therapeuticClass: 'Corticosteroid',
            formulation: 'Tablet',
            systemicCategory: 'Immune System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Corticosteroids',
            strength: '10mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'Inflammatory conditions, allergies',
            contraindications: 'Systemic fungal infections, hypersensitivity',
            sideEffects: 'Increased appetite, weight gain, mood changes',
            interactions: 'NSAIDs, warfarin, diuretics',
            warnings: 'May increase risk of infections, monitor blood pressure and blood sugar',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'S12345',
            description: 'Prednisone is used to treat inflammatory conditions and allergies.',
        },
        {
            id: 100000020,
            activeIngredients: 'Alprazolam 0.5mg',
            inactiveIngredients: 'Lactose, Magnesium Stearate, Microcrystalline Cellulose',
            therapeuticClass: 'Anxiolytic',
            formulation: 'Tablet',
            systemicCategory: 'Nervous System',
            usageDuration: 'PRN',
            targetPopulation: 'Adults',
            drugClass: 'Benzodiazepines',
            strength: '0.5mg',
            dosage: '1 tablet three times daily',
            routeOfAdministration: 'Oral',
            indications: 'Anxiety disorders, panic disorders',
            contraindications: 'Acute narrow-angle glaucoma, hypersensitivity',
            sideEffects: 'Drowsiness, dizziness, dry mouth',
            interactions: 'Alcohol, other CNS depressants, antifungal medications',
            warnings: 'May cause drowsiness, avoid driving or operating heavy machinery',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'T12345',
            description: 'Alprazolam is used to treat anxiety and panic disorders.',
        },
        {
            id: 100000021,
            activeIngredients: 'Clopidogrel 75mg',
            inactiveIngredients: 'Lactose, Magnesium Stearate, Microcrystalline Cellulose',
            therapeuticClass: 'Antiplatelet',
            formulation: 'Tablet',
            systemicCategory: 'Cardiovascular System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Antiplatelet agents',
            strength: '75mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'Prevention of blood clots',
            contraindications: 'Active bleeding, hypersensitivity',
            sideEffects: 'Bleeding, bruising, rash',
            interactions: 'NSAIDs, warfarin, heparin',
            warnings: 'Monitor for signs of bleeding, avoid activities that may cause injury',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'U12345',
            description: 'Clopidogrel is used to prevent blood clots in patients with heart disease.',
        },
        {
            id: 100000022,
            activeIngredients: 'Allopurinol 300mg',
            inactiveIngredients: 'Lactose, Magnesium Stearate, Microcrystalline Cellulose',
            therapeuticClass: 'Antigout',
            formulation: 'Tablet',
            systemicCategory: 'Musculoskeletal System',
            usageDuration: 'Chronic',
            targetPopulation: 'Adults',
            drugClass: 'Xanthine oxidase inhibitors',
            strength: '300mg',
            dosage: '1 tablet daily',
            routeOfAdministration: 'Oral',
            indications: 'Gout, kidney stones',
            contraindications: 'Hypersensitivity to allopurinol',
            sideEffects: 'Rash, gastrointestinal upset, liver enzyme abnormalities',
            interactions: 'Azathioprine, mercaptopurine, ampicillin',
            warnings: 'Monitor liver and kidney function, may cause rash',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'V12345',
            description: 'Allopurinol is used to treat gout and prevent certain types of kidney stones.',
        },
        {
            id: 100000023,
            activeIngredients: 'Cyclobenzaprine 10mg',
            inactiveIngredients: 'Lactose, Magnesium Stearate, Microcrystalline Cellulose',
            therapeuticClass: 'Muscle Relaxant',
            formulation: 'Tablet',
            systemicCategory: 'Musculoskeletal System',
            usageDuration: 'PRN',
            targetPopulation: 'Adults',
            drugClass: 'Muscle relaxants',
            strength: '10mg',
            dosage: '1 tablet three times daily',
            routeOfAdministration: 'Oral',
            indications: 'Muscle spasms',
            contraindications: 'Recent myocardial infarction, hyperthyroidism',
            sideEffects: 'Drowsiness, dry mouth, dizziness',
            interactions: 'MAOIs, alcohol, CNS depressants',
            warnings: 'May cause drowsiness, avoid driving or operating heavy machinery',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'W12345',
            description: 'Cyclobenzaprine is used to treat muscle spasms associated with acute musculoskeletal conditions.',
        },
        {
            id: 100000024,
            activeIngredients: 'Azithromycin 250mg',
            inactiveIngredients: 'Lactose, Magnesium Stearate, Microcrystalline Cellulose',
            therapeuticClass: 'Antibiotic',
            formulation: 'Tablet',
            systemicCategory: 'Respiratory System',
            usageDuration: 'Acute',
            targetPopulation: 'Adults',
            drugClass: 'Macrolides',
            strength: '250mg',
            dosage: '1 tablet daily for 5 days',
            routeOfAdministration: 'Oral',
            indications: 'Bacterial infections',
            contraindications: 'Hypersensitivity to azithromycin',
            sideEffects: 'Nausea, diarrhea, abdominal pain',
            interactions: 'Warfarin, antacids, digoxin',
            warnings: 'May cause gastrointestinal upset, take with food to reduce side effects',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'X12345',
            description: 'Azithromycin is used to treat various types of bacterial infections.',
        },
        {
            id: 100000025,
            activeIngredients: 'Doxycycline 100mg',
            inactiveIngredients: 'Lactose, Magnesium Stearate, Microcrystalline Cellulose',
            therapeuticClass: 'Antibiotic',
            formulation: 'Tablet',
            systemicCategory: 'Respiratory System',
            usageDuration: 'Acute',
            targetPopulation: 'Adults',
            drugClass: 'Tetracyclines',
            strength: '100mg',
            dosage: '1 tablet twice daily',
            routeOfAdministration: 'Oral',
            indications: 'Bacterial infections',
            contraindications: 'Hypersensitivity to doxycycline',
            sideEffects: 'Nausea, diarrhea, photosensitivity',
            interactions: 'Antacids, iron supplements, oral contraceptives',
            warnings: 'May cause photosensitivity, avoid prolonged sun exposure',
            storageConditions: 'Store at room temperature away from moisture and heat',
            approvalDate: '2000-01-01',
            expiryDate: '2024-12-31',
            batchNumber: 'Y12345',
            description: 'Doxycycline is used to treat various types of bacterial infections.',
        },
    ]
};